name: Build-Release-Images

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-release-images:
    name: Build and Release Firmware Images
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build firmware images
        run: 'make images CURL_OPTS="-s"'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openwrt-imagebuilder-*/bin/targets/*/*/openwrt-*.bin
            openwrt-imagebuilder-*/bin/targets/*/*/openwrt-*.manifest
            openwrt-imagebuilder-*/bin/targets/*/*/sha256sums
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
